server:
      port: 8090
      servlet:
             contextPath: /services

jwt:
   secret: covid19

spring:
      datasource:
              driver-class-name: oracle.jdbc.driver.OracleDriver
              url: jdbc:oracle:thin:@localhost:1521:xe
              password: neeraj439
              username: neerajdb
          
      data:
          mongodb:
                 host: localhost
                 port: 27017
                 database: neerajmongodb
                 
logging:
       level:
            org:
               springframework:
                              web:
                                 servlet:
                                        DispatcherServlet: debug
           